name: motion
channels:
  - conda-forge
dependencies:
  - python
  - scipy
  - xarray
  - ezc3d
  - matplotlib
  - bottleneck
  # dev
  - black
  - pytest
  - pytest-cov
  - pip
  - pip:
    - mkdocs
    - mkdocs-material
    - -e .
