name: pyomeca
channels:
  - conda-forge
dependencies:
  - python
  - scipy
  - xarray
  - ezc3d
  - matplotlib
  - bottleneck
  - xlrd
  # dev
  - pip
  - pip:
      - -e .
      - mkdocs
      - mkdocs-material
      - mkdocstrings
      - black
      - pytest
      - pytest-cov
