# Project information
site_name: 'Motion'
site_description: 'A Material Design theme for MkDocs'
site_author: 'Romain Martinez'

# Configuration
theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'teal'
  logo: 'images/logo.svg'
  favicon: 'images/favicon.ico'
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide: user-guide.md
  - Case Studies: case-studies.md
  - About: about.md
  - API reference: doc.md

markdown_extensions:
  - admonition
  - footnotes
  - codehilite

# Repository
repo_name: 'pyomeca/pyomeca'
repo_url: 'https://github.com/pyomeca/pyomeca'

# Copyright
copyright: 'Copyright &copy; 2019 Romain Martinez'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/romainmartinez'
