name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    # every sunday at 14:00 UTC
    - cron:  '0 14 * * SUN'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.6, 3.7, 3.8] # OK: macos, ubuntu [3.6, 3.7, 3.8] | not ok windows 3.7, 3.8
    name: ${{ matrix.os }} - Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@master
      - name: Setup conda
        uses: s-weigand/setup-conda@master
        with:
          activate-conda: true
          update-conda: false
          python-version: ${{ matrix.python-version }}
          conda-channels: default, conda-forge, anaconda
      - run: echo "##[add-path]C:\Miniconda\Library\bin"
      - run: conda env update -f environment.yml -q -n base
      - run: conda info -a
      - run: black --check .
      - run: python -m pytest --cov-report term-missing --color=yes --cov=motion tests
      - name: Coverall
        env:
          COVERALLS_REPO_TOKEN: m0Y1JKhhCecsIkye25oHlA8rmiPDhqocp
        run: |
          pip install coveralls
          coveralls
